class Enigma(object):


    disk1 = [{
        "a": "p",
        "b": "z",
        "c": "t",
        "d": "x",
        "e": "y",
        "f": "v",
        "g": "s",
        "h": "j",
        "i": "q",
        "j": "h",
        "k": "u",
        "l": "w",
        "m": "r",
        "n": "o",
        "o": "n",
        "p": "a",
        "q": "i",
        "r": "m",
        "s": "g",
        "t": "c",
        "u": "k",
        "v": "f",
        "w": "l",
        "x": "d",
        "y": "e",
        "z": "b",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    }, {
        "a": "z",
        "b": "i",
        "c": "m",
        "d": "y",
        "e": "h",
        "f": "x",
        "g": "v",
        "h": "e",
        "i": "b",
        "j": "t",
        "k": "w",
        "l": "o",
        "m": "c",
        "n": "u",
        "o": "l",
        "p": "r",
        "q": "s",
        "r": "p",
        "s": "q",
        "t": "j",
        "u": "n",
        "v": "g",
        "w": "k",
        "x": "f",
        "y": "d",
        "z": "a",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    },
        {
        "a": "s",
        "b": "e",
        "c": "v",
        "d": "p",
        "e": "b",
        "f": "h",
        "g": "w",
        "h": "f",
        "i": "m",
        "j": "u",
        "k": "p",
        "l": "n",
        "m": "i",
        "n": "l",
        "o": "y",
        "p": "k",
        "q": "d",
        "r": "z",
        "s": "a",
        "t": "x",
        "u": "j",
        "v": "c",
        "w": "g",
        "x": "t",
        "y": "o",
        "z": "r",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    },
        {
        "a": "c",
        "b": "l",
        "c": "a",
        "d": "r",
        "e": "t",
        "f": "u",
        "g": "m",
        "h": "v",
        "i": "w",
        "j": "z",
        "k": "q",
        "l": "b",
        "m": "g",
        "n": "y",
        "o": "s",
        "p": "x",
        "q": "k",
        "r": "d",
        "s": "o",
        "t": "e",
        "u": "f",
        "v": "h",
        "w": "i",
        "x": "p",
        "y": "n",
        "z": "j",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    }
    ]
    disk2 = [{
        "a": "p",
        "b": "n",
        "c": "t",
        "d": "k",
        "e": "w",
        "f": "v",
        "g": "r",
        "h": "q",
        "i": "l",
        "j": "y",
        "k": "d",
        "l": "i",
        "m": "x",
        "n": "b",
        "o": "u",
        "p": "a",
        "q": "h",
        "r": "g",
        "s": "z",
        "t": "c",
        "u": "o",
        "v": "f",
        "w": "e",
        "x": "m",
        "y": "j",
        "z": "s",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    }, {
        "a": "c",
        "b": "v",
        "c": "a",
        "d": "i",
        "e": "m",
        "f": "s",
        "g": "l",
        "h": "u",
        "i": "d",
        "j": "k",
        "k": "j",
        "l": "g",
        "m": "e",
        "n": "r",
        "o": "w",
        "p": "q",
        "q": "p",
        "r": "n",
        "s": "f",
        "t": "x",
        "u": "h",
        "v": "b",
        "w": "o",
        "x": "t",
        "y": "z",
        "z": "y",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    },
        {
        "a": "y",
        "b": "e",
        "c": "v",
        "d": "s",
        "e": "b",
        "f": "o",
        "g": "q",
        "h": "l",
        "i": "m",
        "j": "u",
        "k": "r",
        "l": "h",
        "m": "i",
        "n": "p",
        "o": "f",
        "p": "n",
        "q": "g",
        "r": "k",
        "s": "d",
        "t": "x",
        "u": "j",
        "v": "c",
        "w": "z",
        "x": "t",
        "y": "a",
        "z": "w",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    },
        {
        "a": "u",
        "b": "h",
        "c": "r",
        "d": "t",
        "e": "g",
        "f": "j",
        "g": "e",
        "h": "b",
        "i": "w",
        "j": "f",
        "k": "n",
        "l": "y",
        "m": "q",
        "n": "k",
        "o": "s",
        "p": "x",
        "q": "m",
        "r": "c",
        "s": "o",
        "t": "d",
        "u": "a",
        "v": "z",
        "w": "i",
        "x": "p",
        "y": "l",
        "z": "v",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    }
    ]
    disk3 = [{
        "a": "p",
        "b": "s",
        "c": "t",
        "d": "w",
        "e": "z",
        "f": "g",
        "g": "f",
        "h": "o",
        "i": "r",
        "j": "x",
        "k": "n",
        "l": "q",
        "m": "v",
        "n": "k",
        "o": "h",
        "p": "a",
        "q": "l",
        "r": "i",
        "s": "b",
        "t": "c",
        "u": "y",
        "v": "m",
        "w": "d",
        "x": "j",
        "y": "u",
        "z": "e",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    }, {
        "a": "z",
        "b": "i",
        "c": "m",
        "d": "y",
        "e": "h",
        "f": "x",
        "g": "v",
        "h": "e",
        "i": "b",
        "j": "t",
        "k": "w",
        "l": "o",
        "m": "c",
        "n": "u",
        "o": "l",
        "p": "r",
        "q": "s",
        "r": "p",
        "s": "q",
        "t": "j",
        "u": "n",
        "v": "g",
        "w": "k",
        "x": "f",
        "y": "d",
        "z": "a",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    },
        {
        "a": "o",
        "b": "s",
        "c": "v",
        "d": "n",
        "e": "l",
        "f": "k",
        "g": "w",
        "h": "i",
        "i": "h",
        "j": "u",
        "k": "f",
        "l": "e",
        "m": "y",
        "n": "d",
        "o": "a",
        "p": "q",
        "q": "p",
        "r": "z",
        "s": "b",
        "t": "x",
        "u": "j",
        "v": "c",
        "w": "g",
        "x": "t",
        "y": "m",
        "z": "r",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    },
        {
        "a": "s",
        "b": "l",
        "c": "w",
        "d": "k",
        "e": "y",
        "f": "v",
        "g": "q",
        "h": "n",
        "i": "u",
        "j": "z",
        "k": "d",
        "l": "b",
        "m": "o",
        "n": "h",
        "o": "m",
        "p": "x",
        "q": "g",
        "r": "t",
        "s": "a",
        "t": "r",
        "u": "i",
        "v": "f",
        "w": "c",
        "x": "p",
        "y": "e",
        "z": "j",
        " ": " ",
        ";": ";",
        "'": "'",
        "=": "=",
        "?": "?",
        "!": "!",
        ",": ",",
        ":": ":",
        "-": "-",
        "\n":"\n",
        ".":"."
    }
    ]





    def encrypt(self,disk1_position, disk2_position, disk3_position, message):

        msg1=""

        for letter in message:


                l1 = Enigma.disk1[disk1_position].get(letter.lower())
                l1 = Enigma.disk2[disk2_position].get(l1)
                l1 = Enigma.disk3[disk3_position].get(l1)
                #print("status d1 "+str(disk1_position))
                #print("status d2 "+str(disk2_position))
                #print("status d3 "+str(disk3_position)+"\n")
                msg1 = msg1 + str(l1)
                if disk1_position < 3:
                    disk1_position += 1
                else:
                    disk1_position = 0
                    if disk2_position<3:
                        disk2_position+=1
                    else:
                        disk2_position=0
                        if disk3_position<3:
                            disk3_position+=1
                        else:
                            disk3_position=0
                            disk1_position=0
        #print(msg1)
        return msg1

    def decrypt(self,disk1_position, disk2_position, disk3_position, message):


            msg1=""

            for letter in message:


                    l1 = Enigma.disk3[disk3_position].get(letter.lower())
                    l1 = Enigma.disk2[disk2_position].get(l1)
                    l1 = Enigma.disk1[disk1_position].get(l1)
                    #print("status d1 "+str(disk1_position))
                    #print("status d2 "+str(disk2_position))
                    #print("status d3 "+str(disk3_position)+"\n")
                    msg1 = msg1 + str(l1)
                    if disk1_position < 3:
                        disk1_position += 1
                    else:
                        disk1_position = 0
                        if disk2_position<3:
                            disk2_position+=1
                        else:
                            disk2_position=0
                            if disk3_position<3:
                                disk3_position+=1
                            else:
                                disk3_position=0
                                disk1_position=0



            return msg1
